### ISSUE TITLE
Peer review, Hongfan

### ISSUE THREAD

**Issue by HongfanChen** [longyyu/Stats506_FinalProj#1]
Hey, You’ve done a great job! Here’s some suggestions for you to improve your work.
1.	Could improve the organization of your table to be more concise. The table is too long that when I scroll down, I forget the column names. And also it may excess the limit of 3 pages.
2.	Line 233 in final_project.R has only 78 characters, but if you were using -----, I think you should make it to 79 characters?
3.	Since you haven’t upload your discussion part, I cannot review on that.
I have also left a message on Canvas, but that is the same as this one.

**Comment by longyyu** [comment]
Thanks for the suggestions!

1. I made an effort to reorganize table 1 and make it shorter. It is still quite long, because the target variable `wall material` has many levels. But with the columns being `year of construction` categories, the most important comparisons  (i.e., change in the percent of wall materials over time)  are now across rows. 
1. Fixed that. 
1. Already updated conclusion/discussion.
